version: "3.7"

services:


  mysql:
    image: mysql:8.0
    volumes:
      - project-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: project
    ports:
      - "3306:3306"

volumes:
  project-mysql-data: